apiVersion: v1
kind: Service
metadata:
  name: eclipse-mosquitto-bridge-local
spec:
  type: NodePort
  ports:
    - port: 1885
      targetPort: 1885
      nodePort: 31885
  selector:
    app: mosquitto-bridge-local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eclipse-mosquitto-bridge-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-bridge-local
  template:
    metadata:
      labels:
        app: mosquitto-bridge-local
    spec:
      volumes:
      - name: config
        configMap:
          name: eclipse-mosquitto-bridge-local-config      
      containers:
      - name: eclipse-mosquitto
        image: eclipse-mosquitto:1.6
        volumeMounts:
          - mountPath: /mosquitto/config
            name: config
        ports:
          - name: tcp-port
            containerPort: 1885
            protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eclipse-mosquitto-bridge-local-config
data:
    mosquitto.conf: |
      listener 1885

      connection orion-bridge
      address 162.243.172.74:31886
      topic application/# out    
