apiVersion: v1
kind: Service
metadata:
  name: eclipse-mosquitto-bridge-remote
spec:
  type: NodePort
  ports:
    - port: 1886
      targetPort: 1886
      nodePort: 31886
  selector:
    app: mosquitto-bridge-remote

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eclipse-mosquitto-bridge-remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-bridge-remote
  template:
    metadata:
      labels:
        app: mosquitto-bridge-remote
    spec:
      volumes:
      - name: config
        configMap:
          name: eclipse-mosquitto-bridge-remote-config      
      containers:
      - name: eclipse-mosquitto-bridge-remote
        image: eclipse-mosquitto:1.6
        volumeMounts:
          - mountPath: /mosquitto/config
            name: config
        ports:
          - name: tcp-port
            containerPort: 1886
            protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eclipse-mosquitto-bridge-remote-config
data:
    mosquitto.conf: |
      listener 1886     
