apiVersion: v1
kind: Service
metadata:
  name: swamp-iot-agent
spec:
  type: NodePort
  ports:
    - port: 3456
      targetPort: 3456
      nodePort: 31456
  selector:
    app: iot-agent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swamp-iot-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-agent
  template:
    metadata:
      labels:
        app: iot-agent
    spec:      
      containers:
      - name: swamp-iot-agent
        image: ${image}
        ports:
          - name: http-port
            containerPort: 3456       

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb  
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017      
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:      
      containers:
      - name: mongodb
        image: mongo:3.6               
        ports:
          - name: tcp-port
            containerPort: 27017
            protocol: TCP         
      

      
